export interface ICountryItem {
    name: string;
    alpha3: string;
    alpha2: string;
    region: string;
    subregion: string;
    supported_identity_report: boolean;
}

export const countryList: ICountryItem[] = [
    {
        name: 'countries:Switzerland',
        alpha3: 'CHE',
        alpha2: 'CH',
        region: 'Europe',
        subregion: 'Western Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:France',
        alpha3: 'FRA',
        alpha2: 'FR',
        region: 'Europe',
        subregion: 'Western Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:Italy',
        alpha3: 'ITA',
        alpha2: 'IT',
        region: 'Europe',
        subregion: 'Southern Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:Germany',
        alpha3: 'DEU',
        alpha2: 'DE',
        region: 'Europe',
        subregion: 'Western Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:Afghanistan',
        alpha3: 'AFG',
        alpha2: 'AF',
        region: 'Asia',
        subregion: 'Southern Asia',
        supported_identity_report: true,
    },
    {
        name: 'countries:Albania',
        alpha3: 'ALB',
        alpha2: 'AL',
        region: 'Europe',
        subregion: 'Southern Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:Algeria',
        alpha3: 'DZA',
        alpha2: 'DZ',
        region: 'Africa',
        subregion: 'Northern Africa',
        supported_identity_report: true,
    },
    {
        name: 'countries:American Samoa',
        alpha3: 'ASM',
        alpha2: 'AS',
        region: 'Oceania',
        subregion: 'Polynesia',
        supported_identity_report: false,
    },
    {
        name: 'countries:Andorra',
        alpha3: 'AND',
        alpha2: 'AD',
        region: 'Europe',
        subregion: 'Southern Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:Angola',
        alpha3: 'AGO',
        alpha2: 'AO',
        region: 'Africa',
        subregion: 'Middle Africa',
        supported_identity_report: false,
    },
    {
        name: 'countries:Anguilla',
        alpha3: 'AIA',
        alpha2: 'AI',
        region: 'Americas',
        subregion: 'Caribbean',
        supported_identity_report: false,
    },
    {
        name: 'countries:Antarctica',
        alpha3: 'ATA',
        alpha2: 'AQ',
        region: '',
        subregion: '',
        supported_identity_report: false,
    },
    {
        name: 'countries:Antigua and Barbuda',
        alpha3: 'ATG',
        alpha2: 'AG',
        region: 'Americas',
        subregion: 'Caribbean',
        supported_identity_report: true,
    },
    {
        name: 'countries:Argentina',
        alpha3: 'ARG',
        alpha2: 'AR',
        region: 'Americas',
        subregion: 'South America',
        supported_identity_report: true,
    },
    {
        name: 'countries:Armenia',
        alpha3: 'ARM',
        alpha2: 'AM',
        region: 'Asia',
        subregion: 'Western Asia',
        supported_identity_report: true,
    },
    {
        name: 'countries:Aruba',
        alpha3: 'ABW',
        alpha2: 'AW',
        region: 'Americas',
        subregion: 'Caribbean',
        supported_identity_report: true,
    },
    {
        name: 'countries:Australia',
        alpha3: 'AUS',
        alpha2: 'AU',
        region: 'Oceania',
        subregion: 'Australia and New Zealand',
        supported_identity_report: true,
    },
    {
        name: 'countries:Austria',
        alpha3: 'AUT',
        alpha2: 'AT',
        region: 'Europe',
        subregion: 'Western Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:Azerbaijan',
        alpha3: 'AZE',
        alpha2: 'AZ',
        region: 'Asia',
        subregion: 'Western Asia',
        supported_identity_report: true,
    },
    {
        name: 'countries:Bahamas',
        alpha3: 'BHS',
        alpha2: 'BS',
        region: 'Americas',
        subregion: 'Caribbean',
        supported_identity_report: false,
    },
    {
        name: 'countries:Bahrain',
        alpha3: 'BHR',
        alpha2: 'BH',
        region: 'Asia',
        subregion: 'Western Asia',
        supported_identity_report: true,
    },
    {
        name: 'countries:Bangladesh',
        alpha3: 'BGD',
        alpha2: 'BD',
        region: 'Asia',
        subregion: 'Southern Asia',
        supported_identity_report: false,
    },
    {
        name: 'countries:Barbados',
        alpha3: 'BRB',
        alpha2: 'BB',
        region: 'Americas',
        subregion: 'Caribbean',
        supported_identity_report: true,
    },
    {
        name: 'countries:Belarus',
        alpha3: 'BLR',
        alpha2: 'BY',
        region: 'Europe',
        subregion: 'Eastern Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:Belgium',
        alpha3: 'BEL',
        alpha2: 'BE',
        region: 'Europe',
        subregion: 'Western Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:Belize',
        alpha3: 'BLZ',
        alpha2: 'BZ',
        region: 'Americas',
        subregion: 'Central America',
        supported_identity_report: true,
    },
    {
        name: 'countries:Benin',
        alpha3: 'BEN',
        alpha2: 'BJ',
        region: 'Africa',
        subregion: 'Western Africa',
        supported_identity_report: true,
    },
    {
        name: 'countries:Bermuda',
        alpha3: 'BMU',
        alpha2: 'BM',
        region: 'Americas',
        subregion: 'Northern America',
        supported_identity_report: true,
    },
    {
        name: 'countries:Bhutan',
        alpha3: 'BTN',
        alpha2: 'BT',
        region: 'Asia',
        subregion: 'Southern Asia',
        supported_identity_report: true,
    },
    {
        name: 'countries:Bolivia (Plurinational State of)',
        alpha3: 'BOL',
        alpha2: 'BO',
        region: 'Americas',
        subregion: 'South America',
        supported_identity_report: false,
    },
    {
        name: 'countries:Bonaire, Sint Eustatius and Saba',
        alpha3: 'BES',
        alpha2: 'NL',
        region: 'Americas',
        subregion: 'Caribbean',
        supported_identity_report: false,
    },
    {
        name: 'countries:Bosnia and Herzegovina',
        alpha3: 'BIH',
        alpha2: 'BA',
        region: 'Europe',
        subregion: 'Southern Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:Botswana',
        alpha3: 'BWA',
        alpha2: 'BW',
        region: 'Africa',
        subregion: 'Southern Africa',
        supported_identity_report: false,
    },
    {
        name: 'countries:Bouvet Island',
        alpha3: 'BVT',
        alpha2: 'NO',
        region: '',
        subregion: '',
        supported_identity_report: false,
    },
    {
        name: 'countries:Brazil',
        alpha3: 'BRA',
        alpha2: 'BR',
        region: 'Americas',
        subregion: 'South America',
        supported_identity_report: true,
    },
    {
        name: 'countries:British Indian Ocean Territory',
        alpha3: 'IOT',
        alpha2: 'GB',
        region: 'Africa',
        subregion: 'Eastern Africa',
        supported_identity_report: false,
    },
    {
        name: 'countries:Brunei Darussalam',
        alpha3: 'BRN',
        alpha2: 'BN',
        region: 'Asia',
        subregion: 'South-Eastern Asia',
        supported_identity_report: true,
    },
    {
        name: 'countries:Bulgaria',
        alpha3: 'BGR',
        alpha2: 'BG',
        region: 'Europe',
        subregion: 'Eastern Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:Burkina Faso',
        alpha3: 'BFA',
        alpha2: 'BF',
        region: 'Africa',
        subregion: 'Western Africa',
        supported_identity_report: true,
    },
    {
        name: 'countries:Burundi',
        alpha3: 'BDI',
        alpha2: 'BI',
        region: 'Africa',
        subregion: 'Eastern Africa',
        supported_identity_report: true,
    },
    {
        name: 'countries:Cabo Verde',
        alpha3: 'CPV',
        alpha2: 'CV',
        region: 'Africa',
        subregion: 'Western Africa',
        supported_identity_report: false,
    },
    {
        name: 'countries:Cambodia',
        alpha3: 'KHM',
        alpha2: 'KH',
        region: 'Asia',
        subregion: 'South-Eastern Asia',
        supported_identity_report: true,
    },
    {
        name: 'countries:Cameroon',
        alpha3: 'CMR',
        alpha2: 'CM',
        region: 'Africa',
        subregion: 'Middle Africa',
        supported_identity_report: true,
    },
    {
        name: 'countries:Canada',
        alpha3: 'CAN',
        alpha2: 'CA',
        region: 'Americas',
        subregion: 'Northern America',
        supported_identity_report: true,
    },
    {
        name: 'countries:Cayman Islands',
        alpha3: 'CYM',
        alpha2: 'KY',
        region: 'Americas',
        subregion: 'Caribbean',
        supported_identity_report: true,
    },
    {
        name: 'countries:Central African Republic',
        alpha3: 'CAF',
        alpha2: 'CF',
        region: 'Africa',
        subregion: 'Middle Africa',
        supported_identity_report: true,
    },
    {
        name: 'countries:Chad',
        alpha3: 'TCD',
        alpha2: 'TD',
        region: 'Africa',
        subregion: 'Middle Africa',
        supported_identity_report: false,
    },
    {
        name: 'countries:Chile',
        alpha3: 'CHL',
        alpha2: 'CL',
        region: 'Americas',
        subregion: 'South America',
        supported_identity_report: true,
    },
    {
        name: 'countries:China',
        alpha3: 'CHN',
        alpha2: 'CN',
        region: 'Asia',
        subregion: 'Eastern Asia',
        supported_identity_report: true,
    },
    {
        name: 'countries:Christmas Island',
        alpha3: 'CXR',
        alpha2: 'CX',
        region: 'Oceania',
        subregion: 'Australia and New Zealand',
        supported_identity_report: false,
    },
    {
        name: 'countries:Cocos (Keeling) Islands',
        alpha3: 'CCK',
        alpha2: 'CC',
        region: 'Oceania',
        subregion: 'Australia and New Zealand',
        supported_identity_report: false,
    },
    {
        name: 'countries:Colombia',
        alpha3: 'COL',
        alpha2: 'CO',
        region: 'Americas',
        subregion: 'South America',
        supported_identity_report: true,
    },
    {
        name: 'countries:Comoros',
        alpha3: 'COM',
        alpha2: 'KM',
        region: 'Africa',
        subregion: 'Eastern Africa',
        supported_identity_report: false,
    },
    {
        name: 'countries:Congo',
        alpha3: 'COG',
        alpha2: 'CG',
        region: 'Africa',
        subregion: 'Middle Africa',
        supported_identity_report: true,
    },
    {
        name: 'countries:Congo (Democratic Republic of the)',
        alpha3: 'COD',
        alpha2: 'CD',
        region: 'Africa',
        subregion: 'Middle Africa',
        supported_identity_report: false,
    },
    {
        name: 'countries:Cook Islands',
        alpha3: 'COK',
        alpha2: 'CK',
        region: 'Oceania',
        subregion: 'Polynesia',
        supported_identity_report: true,
    },
    {
        name: 'countries:Costa Rica',
        alpha3: 'CRI',
        alpha2: 'CR',
        region: 'Americas',
        subregion: 'Central America',
        supported_identity_report: true,
    },
    {
        name: 'countries:Croatia',
        alpha3: 'HRV',
        alpha2: 'HR',
        region: 'Europe',
        subregion: 'Southern Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:Cuba',
        alpha3: 'CUB',
        alpha2: 'CU',
        region: 'Americas',
        subregion: 'Caribbean',
        supported_identity_report: true,
    },
    {
        name: 'countries:Curaçao',
        alpha3: 'CUW',
        alpha2: 'CW',
        region: 'Americas',
        subregion: 'Caribbean',
        supported_identity_report: false,
    },
    {
        name: 'countries:Cyprus',
        alpha3: 'CYP',
        alpha2: 'CY',
        region: 'Asia',
        subregion: 'Western Asia',
        supported_identity_report: true,
    },
    {
        name: 'countries:Czechia',
        alpha3: 'CZE',
        alpha2: 'CZ',
        region: 'Europe',
        subregion: 'Eastern Europe',
        supported_identity_report: true,
    },
    {
        name: "Côte d'Ivoire",
        alpha3: 'CIV',
        alpha2: 'CI',
        region: 'Africa',
        subregion: 'Western Africa',
        supported_identity_report: true,
    },
    {
        name: 'countries:Denmark',
        alpha3: 'DNK',
        alpha2: 'DK',
        region: 'Europe',
        subregion: 'Northern Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:Djibouti',
        alpha3: 'DJI',
        alpha2: 'DJ',
        region: 'Africa',
        subregion: 'Eastern Africa',
        supported_identity_report: true,
    },
    {
        name: 'countries:Dominica',
        alpha3: 'DMA',
        alpha2: 'DM',
        region: 'Americas',
        subregion: 'Caribbean',
        supported_identity_report: true,
    },
    {
        name: 'countries:Dominican Republic',
        alpha3: 'DOM',
        alpha2: 'DO',
        region: 'Americas',
        subregion: 'Caribbean',
        supported_identity_report: true,
    },
    {
        name: 'countries:Ecuador',
        alpha3: 'ECU',
        alpha2: 'EC',
        region: 'Americas',
        subregion: 'South America',
        supported_identity_report: true,
    },
    {
        name: 'countries:Egypt',
        alpha3: 'EGY',
        alpha2: 'EG',
        region: 'Africa',
        subregion: 'Northern Africa',
        supported_identity_report: true,
    },
    {
        name: 'countries:El Salvador',
        alpha3: 'SLV',
        alpha2: 'SV',
        region: 'Americas',
        subregion: 'Central America',
        supported_identity_report: true,
    },
    {
        name: 'countries:Equatorial Guinea',
        alpha3: 'GNQ',
        alpha2: 'GQ',
        region: 'Africa',
        subregion: 'Middle Africa',
        supported_identity_report: true,
    },
    {
        name: 'countries:Eritrea',
        alpha3: 'ERI',
        alpha2: 'ER',
        region: 'Africa',
        subregion: 'Eastern Africa',
        supported_identity_report: false,
    },
    {
        name: 'countries:Estonia',
        alpha3: 'EST',
        alpha2: 'EE',
        region: 'Europe',
        subregion: 'Northern Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:Ethiopia',
        alpha3: 'ETH',
        alpha2: 'ET',
        region: 'Africa',
        subregion: 'Eastern Africa',
        supported_identity_report: true,
    },
    {
        name: 'countries:Falkland Islands (Malvinas)',
        alpha3: 'FLK',
        alpha2: 'FK',
        region: 'Americas',
        subregion: 'South America',
        supported_identity_report: false,
    },
    {
        name: 'countries:Faroe Islands',
        alpha3: 'FRO',
        alpha2: 'FO',
        region: 'Europe',
        subregion: 'Northern Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:Fiji',
        alpha3: 'FJI',
        alpha2: 'FJ',
        region: 'Oceania',
        subregion: 'Melanesia',
        supported_identity_report: true,
    },
    {
        name: 'countries:Finland',
        alpha3: 'FIN',
        alpha2: 'FI',
        region: 'Europe',
        subregion: 'Northern Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:French Guiana',
        alpha3: 'GUF',
        alpha2: 'FR',
        region: 'Americas',
        subregion: 'South America',
        supported_identity_report: false,
    },
    {
        name: 'countries:French Polynesia',
        alpha3: 'PYF',
        alpha2: 'PF',
        region: 'Oceania',
        subregion: 'Polynesia',
        supported_identity_report: false,
    },
    {
        name: 'countries:French Southern Territories',
        alpha3: 'ATF',
        alpha2: 'TF',
        region: '',
        subregion: '',
        supported_identity_report: false,
    },
    {
        name: 'countries:Gabon',
        alpha3: 'GAB',
        alpha2: 'GA',
        region: 'Africa',
        subregion: 'Middle Africa',
        supported_identity_report: true,
    },
    {
        name: 'countries:Gambia',
        alpha3: 'GMB',
        alpha2: 'GM',
        region: 'Africa',
        subregion: 'Western Africa',
        supported_identity_report: false,
    },
    {
        name: 'countries:Georgia',
        alpha3: 'GEO',
        alpha2: 'GE',
        region: 'Asia',
        subregion: 'Western Asia',
        supported_identity_report: true,
    },
    {
        name: 'countries:Ghana',
        alpha3: 'GHA',
        alpha2: 'GH',
        region: 'Africa',
        subregion: 'Western Africa',
        supported_identity_report: false,
    },
    {
        name: 'countries:Gibraltar',
        alpha3: 'GIB',
        alpha2: 'GI',
        region: 'Europe',
        subregion: 'Southern Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:Greece',
        alpha3: 'GRC',
        alpha2: 'GR',
        region: 'Europe',
        subregion: 'Southern Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:Greenland',
        alpha3: 'GRL',
        alpha2: 'GL',
        region: 'Americas',
        subregion: 'Northern America',
        supported_identity_report: false,
    },
    {
        name: 'countries:Grenada',
        alpha3: 'GRD',
        alpha2: 'GD',
        region: 'Americas',
        subregion: 'Caribbean',
        supported_identity_report: true,
    },
    {
        name: 'countries:Guadeloupe',
        alpha3: 'GLP',
        alpha2: 'FR',
        region: 'Americas',
        subregion: 'Caribbean',
        supported_identity_report: false,
    },
    {
        name: 'countries:Guam',
        alpha3: 'GUM',
        alpha2: 'GU',
        region: 'Oceania',
        subregion: 'Micronesia',
        supported_identity_report: false,
    },
    {
        name: 'countries:Guatemala',
        alpha3: 'GTM',
        alpha2: 'GT',
        region: 'Americas',
        subregion: 'Central America',
        supported_identity_report: true,
    },
    {
        name: 'countries:Guernsey',
        alpha3: 'GGY',
        alpha2: 'GG',
        region: 'Europe',
        subregion: 'Northern Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:Guinea',
        alpha3: 'GIN',
        alpha2: 'GN',
        region: 'Africa',
        subregion: 'Western Africa',
        supported_identity_report: true,
    },
    {
        name: 'countries:Guinea-Bissau',
        alpha3: 'GNB',
        alpha2: 'GW',
        region: 'Africa',
        subregion: 'Western Africa',
        supported_identity_report: false,
    },
    {
        name: 'countries:Guyana',
        alpha3: 'GUY',
        alpha2: 'GY',
        region: 'Americas',
        subregion: 'South America',
        supported_identity_report: false,
    },
    {
        name: 'countries:Haiti',
        alpha3: 'HTI',
        alpha2: 'HT',
        region: 'Americas',
        subregion: 'Caribbean',
        supported_identity_report: false,
    },
    {
        name: 'countries:Heard Island and McDonald Islands',
        alpha3: 'HMD',
        alpha2: 'AU',
        region: '',
        subregion: '',
        supported_identity_report: false,
    },
    {
        name: 'countries:Holy See',
        alpha3: 'VAT',
        alpha2: 'VA',
        region: 'Europe',
        subregion: 'Southern Europe',
        supported_identity_report: false,
    },
    {
        name: 'countries:Honduras',
        alpha3: 'HND',
        alpha2: 'HN',
        region: 'Americas',
        subregion: 'Central America',
        supported_identity_report: true,
    },
    {
        name: 'countries:Hong Kong',
        alpha3: 'HKG',
        alpha2: 'HK',
        region: 'Asia',
        subregion: 'Eastern Asia',
        supported_identity_report: true,
    },
    {
        name: 'countries:Hungary',
        alpha3: 'HUN',
        alpha2: 'HU',
        region: 'Europe',
        subregion: 'Eastern Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:Iceland',
        alpha3: 'ISL',
        alpha2: 'IS',
        region: 'Europe',
        subregion: 'Northern Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:India',
        alpha3: 'IND',
        alpha2: 'IN',
        region: 'Asia',
        subregion: 'Southern Asia',
        supported_identity_report: true,
    },
    {
        name: 'countries:Indonesia',
        alpha3: 'IDN',
        alpha2: 'ID',
        region: 'Asia',
        subregion: 'South-Eastern Asia',
        supported_identity_report: true,
    },
    {
        name: 'countries:Iran (Islamic Republic of)',
        alpha3: 'IRN',
        alpha2: 'IR',
        region: 'Asia',
        subregion: 'Southern Asia',
        supported_identity_report: true,
    },
    {
        name: 'countries:Iraq',
        alpha3: 'IRQ',
        alpha2: 'IQ',
        region: 'Asia',
        subregion: 'Western Asia',
        supported_identity_report: false,
    },
    {
        name: 'countries:Ireland',
        alpha3: 'IRL',
        alpha2: 'IE',
        region: 'Europe',
        subregion: 'Northern Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:Isle of Man',
        alpha3: 'IMN',
        alpha2: 'IM',
        region: 'Europe',
        subregion: 'Northern Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:Israel',
        alpha3: 'ISR',
        alpha2: 'IL',
        region: 'Asia',
        subregion: 'Western Asia',
        supported_identity_report: true,
    },
    {
        name: 'countries:Jamaica',
        alpha3: 'JAM',
        alpha2: 'JM',
        region: 'Americas',
        subregion: 'Caribbean',
        supported_identity_report: true,
    },
    {
        name: 'countries:Japan',
        alpha3: 'JPN',
        alpha2: 'JP',
        region: 'Asia',
        subregion: 'Eastern Asia',
        supported_identity_report: true,
    },
    {
        name: 'countries:Jersey',
        alpha3: 'JEY',
        alpha2: 'JE',
        region: 'Europe',
        subregion: 'Northern Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:Jordan',
        alpha3: 'JOR',
        alpha2: 'JO',
        region: 'Asia',
        subregion: 'Western Asia',
        supported_identity_report: false,
    },
    {
        name: 'countries:Kazakhstan',
        alpha3: 'KAZ',
        alpha2: 'KZ',
        region: 'Asia',
        subregion: 'Central Asia',
        supported_identity_report: true,
    },
    {
        name: 'countries:Kenya',
        alpha3: 'KEN',
        alpha2: 'KE',
        region: 'Africa',
        subregion: 'Eastern Africa',
        supported_identity_report: true,
    },
    {
        name: 'countries:Kiribati',
        alpha3: 'KIR',
        alpha2: 'KI',
        region: 'Oceania',
        subregion: 'Micronesia',
        supported_identity_report: false,
    },
    {
        name: "Korea (Democratic People's Republic of)",
        alpha3: 'PRK',
        alpha2: 'KP',
        region: 'Asia',
        subregion: 'Eastern Asia',
        supported_identity_report: false,
    },
    {
        name: 'countries:Korea (Republic of)',
        alpha3: 'KOR',
        alpha2: 'KR',
        region: 'Asia',
        subregion: 'Eastern Asia',
        supported_identity_report: true,
    },
    {
        name: 'countries:Kuwait',
        alpha3: 'KWT',
        alpha2: 'KW',
        region: 'Asia',
        subregion: 'Western Asia',
        supported_identity_report: true,
    },
    {
        name: 'countries:Kyrgyzstan',
        alpha3: 'KGZ',
        alpha2: 'KG',
        region: 'Asia',
        subregion: 'Central Asia',
        supported_identity_report: true,
    },
    {
        name: "Lao People's Democratic Republic",
        alpha3: 'LAO',
        alpha2: 'LA',
        region: 'Asia',
        subregion: 'South-Eastern Asia',
        supported_identity_report: false,
    },
    {
        name: 'countries:Latvia',
        alpha3: 'LVA',
        alpha2: 'LV',
        region: 'Europe',
        subregion: 'Northern Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:Lebanon',
        alpha3: 'LBN',
        alpha2: 'LB',
        region: 'Asia',
        subregion: 'Western Asia',
        supported_identity_report: true,
    },
    {
        name: 'countries:Lesotho',
        alpha3: 'LSO',
        alpha2: 'LS',
        region: 'Africa',
        subregion: 'Southern Africa',
        supported_identity_report: true,
    },
    {
        name: 'countries:Liberia',
        alpha3: 'LBR',
        alpha2: 'LR',
        region: 'Africa',
        subregion: 'Western Africa',
        supported_identity_report: false,
    },
    {
        name: 'countries:Libya',
        alpha3: 'LBY',
        alpha2: 'LY',
        region: 'Africa',
        subregion: 'Northern Africa',
        supported_identity_report: true,
    },
    {
        name: 'countries:Liechtenstein',
        alpha3: 'LIE',
        alpha2: 'LI',
        region: 'Europe',
        subregion: 'Western Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:Lithuania',
        alpha3: 'LTU',
        alpha2: 'LT',
        region: 'Europe',
        subregion: 'Northern Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:Luxembourg',
        alpha3: 'LUX',
        alpha2: 'LU',
        region: 'Europe',
        subregion: 'Western Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:Macao',
        alpha3: 'MAC',
        alpha2: 'MO',
        region: 'Asia',
        subregion: 'Eastern Asia',
        supported_identity_report: false,
    },
    {
        name: 'countries:Macedonia (the former Yugoslav Republic of)',
        alpha3: 'MKD',
        alpha2: 'MK',
        region: 'Europe',
        subregion: 'Southern Europe',
        supported_identity_report: false,
    },
    {
        name: 'countries:Madagascar',
        alpha3: 'MDG',
        alpha2: 'MG',
        region: 'Africa',
        subregion: 'Eastern Africa',
        supported_identity_report: false,
    },
    {
        name: 'countries:Malawi',
        alpha3: 'MWI',
        alpha2: 'MW',
        region: 'Africa',
        subregion: 'Eastern Africa',
        supported_identity_report: true,
    },
    {
        name: 'countries:Malaysia',
        alpha3: 'MYS',
        alpha2: 'MY',
        region: 'Asia',
        subregion: 'South-Eastern Asia',
        supported_identity_report: true,
    },
    {
        name: 'countries:Maldives',
        alpha3: 'MDV',
        alpha2: 'MV',
        region: 'Asia',
        subregion: 'Southern Asia',
        supported_identity_report: false,
    },
    {
        name: 'countries:Mali',
        alpha3: 'MLI',
        alpha2: 'ML',
        region: 'Africa',
        subregion: 'Western Africa',
        supported_identity_report: true,
    },
    {
        name: 'countries:Malta',
        alpha3: 'MLT',
        alpha2: 'MT',
        region: 'Europe',
        subregion: 'Southern Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:Marshall Islands',
        alpha3: 'MHL',
        alpha2: 'MH',
        region: 'Oceania',
        subregion: 'Micronesia',
        supported_identity_report: false,
    },
    {
        name: 'countries:Martinique',
        alpha3: 'MTQ',
        alpha2: 'FR',
        region: 'Americas',
        subregion: 'Caribbean',
        supported_identity_report: false,
    },
    {
        name: 'countries:Mauritania',
        alpha3: 'MRT',
        alpha2: 'MR',
        region: 'Africa',
        subregion: 'Western Africa',
        supported_identity_report: true,
    },
    {
        name: 'countries:Mauritius',
        alpha3: 'MUS',
        alpha2: 'MU',
        region: 'Africa',
        subregion: 'Eastern Africa',
        supported_identity_report: false,
    },
    {
        name: 'countries:Mayotte',
        alpha3: 'MYT',
        alpha2: 'YT',
        region: 'Africa',
        subregion: 'Eastern Africa',
        supported_identity_report: false,
    },
    {
        name: 'countries:Mexico',
        alpha3: 'MEX',
        alpha2: 'MX',
        region: 'Americas',
        subregion: 'Central America',
        supported_identity_report: true,
    },
    {
        name: 'countries:Micronesia (Federated States of)',
        alpha3: 'FSM',
        alpha2: 'FM',
        region: 'Oceania',
        subregion: 'Micronesia',
        supported_identity_report: false,
    },
    {
        name: 'countries:Moldova (Republic of)',
        alpha3: 'MDA',
        alpha2: 'MD',
        region: 'Europe',
        subregion: 'Eastern Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:Monaco',
        alpha3: 'MCO',
        alpha2: 'MC',
        region: 'Europe',
        subregion: 'Western Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:Mongolia',
        alpha3: 'MNG',
        alpha2: 'MN',
        region: 'Asia',
        subregion: 'Eastern Asia',
        supported_identity_report: false,
    },
    {
        name: 'countries:Montenegro',
        alpha3: 'MNE',
        alpha2: 'ME',
        region: 'Europe',
        subregion: 'Southern Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:Montserrat',
        alpha3: 'MSR',
        alpha2: 'MS',
        region: 'Americas',
        subregion: 'Caribbean',
        supported_identity_report: true,
    },
    {
        name: 'countries:Morocco',
        alpha3: 'MAR',
        alpha2: 'MA',
        region: 'Africa',
        subregion: 'Northern Africa',
        supported_identity_report: true,
    },
    {
        name: 'countries:Mozambique',
        alpha3: 'MOZ',
        alpha2: 'MZ',
        region: 'Africa',
        subregion: 'Eastern Africa',
        supported_identity_report: false,
    },
    {
        name: 'countries:Myanmar',
        alpha3: 'MMR',
        alpha2: 'MM',
        region: 'Asia',
        subregion: 'South-Eastern Asia',
        supported_identity_report: false,
    },
    {
        name: 'countries:Namibia',
        alpha3: 'NAM',
        alpha2: 'NA',
        region: 'Africa',
        subregion: 'Southern Africa',
        supported_identity_report: true,
    },
    {
        name: 'countries:Nauru',
        alpha3: 'NRU',
        alpha2: 'NR',
        region: 'Oceania',
        subregion: 'Micronesia',
        supported_identity_report: false,
    },
    {
        name: 'countries:Nepal',
        alpha3: 'NPL',
        alpha2: 'NP',
        region: 'Asia',
        subregion: 'Southern Asia',
        supported_identity_report: true,
    },
    {
        name: 'countries:Netherlands',
        alpha3: 'NLD',
        alpha2: 'NL',
        region: 'Europe',
        subregion: 'Western Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:New Caledonia',
        alpha3: 'NCL',
        alpha2: 'NC',
        region: 'Oceania',
        subregion: 'Melanesia',
        supported_identity_report: false,
    },
    {
        name: 'countries:New Zealand',
        alpha3: 'NZL',
        alpha2: 'NZ',
        region: 'Oceania',
        subregion: 'Australia and New Zealand',
        supported_identity_report: true,
    },
    {
        name: 'countries:Nicaragua',
        alpha3: 'NIC',
        alpha2: 'NI',
        region: 'Americas',
        subregion: 'Central America',
        supported_identity_report: true,
    },
    {
        name: 'countries:Niger',
        alpha3: 'NER',
        alpha2: 'NE',
        region: 'Africa',
        subregion: 'Western Africa',
        supported_identity_report: true,
    },
    {
        name: 'countries:Nigeria',
        alpha3: 'NGA',
        alpha2: 'NG',
        region: 'Africa',
        subregion: 'Western Africa',
        supported_identity_report: true,
    },
    {
        name: 'countries:Niue',
        alpha3: 'NIU',
        alpha2: 'NU',
        region: 'Oceania',
        subregion: 'Polynesia',
        supported_identity_report: false,
    },
    {
        name: 'countries:Norfolk Island',
        alpha3: 'NFK',
        alpha2: 'NF',
        region: 'Oceania',
        subregion: 'Australia and New Zealand',
        supported_identity_report: true,
    },
    {
        name: 'countries:Northern Mariana Islands',
        alpha3: 'MNP',
        alpha2: 'MP',
        region: 'Oceania',
        subregion: 'Micronesia',
        supported_identity_report: false,
    },
    {
        name: 'countries:Norway',
        alpha3: 'NOR',
        alpha2: 'NO',
        region: 'Europe',
        subregion: 'Northern Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:Oman',
        alpha3: 'OMN',
        alpha2: 'OM',
        region: 'Asia',
        subregion: 'Western Asia',
        supported_identity_report: true,
    },
    {
        name: 'countries:Pakistan',
        alpha3: 'PAK',
        alpha2: 'PK',
        region: 'Asia',
        subregion: 'Southern Asia',
        supported_identity_report: true,
    },
    {
        name: 'countries:Palau',
        alpha3: 'PLW',
        alpha2: 'PW',
        region: 'Oceania',
        subregion: 'Micronesia',
        supported_identity_report: false,
    },
    {
        name: 'countries:Palestine, State of',
        alpha3: 'PSE',
        alpha2: 'PS',
        region: 'Asia',
        subregion: 'Western Asia',
        supported_identity_report: true,
    },
    {
        name: 'countries:Panama',
        alpha3: 'PAN',
        alpha2: 'PA',
        region: 'Americas',
        subregion: 'Central America',
        supported_identity_report: true,
    },
    {
        name: 'countries:Papua New Guinea',
        alpha3: 'PNG',
        alpha2: 'PG',
        region: 'Oceania',
        subregion: 'Melanesia',
        supported_identity_report: false,
    },
    {
        name: 'countries:Paraguay',
        alpha3: 'PRY',
        alpha2: 'PY',
        region: 'Americas',
        subregion: 'South America',
        supported_identity_report: true,
    },
    {
        name: 'countries:Peru',
        alpha3: 'PER',
        alpha2: 'PE',
        region: 'Americas',
        subregion: 'South America',
        supported_identity_report: true,
    },
    {
        name: 'countries:Philippines',
        alpha3: 'PHL',
        alpha2: 'PH',
        region: 'Asia',
        subregion: 'South-Eastern Asia',
        supported_identity_report: true,
    },
    {
        name: 'countries:Pitcairn',
        alpha3: 'PCN',
        alpha2: 'PN',
        region: 'Oceania',
        subregion: 'Polynesia',
        supported_identity_report: false,
    },
    {
        name: 'countries:Poland',
        alpha3: 'POL',
        alpha2: 'PL',
        region: 'Europe',
        subregion: 'Eastern Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:Portugal',
        alpha3: 'PRT',
        alpha2: 'PT',
        region: 'Europe',
        subregion: 'Southern Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:Puerto Rico',
        alpha3: 'PRI',
        alpha2: 'PR',
        region: 'Americas',
        subregion: 'Caribbean',
        supported_identity_report: true,
    },
    {
        name: 'countries:Qatar',
        alpha3: 'QAT',
        alpha2: 'QA',
        region: 'Asia',
        subregion: 'Western Asia',
        supported_identity_report: true,
    },
    {
        name: 'countries:Romania',
        alpha3: 'ROU',
        alpha2: 'RO',
        region: 'Europe',
        subregion: 'Eastern Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:Russian Federation',
        alpha3: 'RUS',
        alpha2: 'RU',
        region: 'Europe',
        subregion: 'Eastern Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:Rwanda',
        alpha3: 'RWA',
        alpha2: 'RW',
        region: 'Africa',
        subregion: 'Eastern Africa',
        supported_identity_report: false,
    },
    {
        name: 'countries:Réunion',
        alpha3: 'REU',
        alpha2: 'FR',
        region: 'Africa',
        subregion: 'Eastern Africa',
        supported_identity_report: false,
    },
    {
        name: 'countries:Saint Barthélemy',
        alpha3: 'BLM',
        alpha2: 'BL',
        region: 'Americas',
        subregion: 'Caribbean',
        supported_identity_report: false,
    },
    {
        name: 'countries:Saint Helena, Ascension and Tristan da Cunha',
        alpha3: 'SHN',
        alpha2: 'SH',
        region: 'Africa',
        subregion: 'Western Africa',
        supported_identity_report: false,
    },
    {
        name: 'countries:Saint Kitts and Nevis',
        alpha3: 'KNA',
        alpha2: 'KN',
        region: 'Americas',
        subregion: 'Caribbean',
        supported_identity_report: true,
    },
    {
        name: 'countries:Saint Lucia',
        alpha3: 'LCA',
        alpha2: 'LC',
        region: 'Americas',
        subregion: 'Caribbean',
        supported_identity_report: true,
    },
    {
        name: 'countries:Saint Martin (French part)',
        alpha3: 'MAF',
        alpha2: 'MF',
        region: 'Americas',
        subregion: 'Caribbean',
        supported_identity_report: false,
    },
    {
        name: 'countries:Saint Pierre and Miquelon',
        alpha3: 'SPM',
        alpha2: 'FR',
        region: 'Americas',
        subregion: 'Northern America',
        supported_identity_report: false,
    },
    {
        name: 'countries:Saint Vincent and the Grenadines',
        alpha3: 'VCT',
        alpha2: 'VC',
        region: 'Americas',
        subregion: 'Caribbean',
        supported_identity_report: true,
    },
    {
        name: 'countries:Samoa',
        alpha3: 'WSM',
        alpha2: 'WS',
        region: 'Oceania',
        subregion: 'Polynesia',
        supported_identity_report: true,
    },
    {
        name: 'countries:San Marino',
        alpha3: 'SMR',
        alpha2: 'SM',
        region: 'Europe',
        subregion: 'Southern Europe',
        supported_identity_report: false,
    },
    {
        name: 'countries:Sao Tome and Principe',
        alpha3: 'STP',
        alpha2: 'ST',
        region: 'Africa',
        subregion: 'Middle Africa',
        supported_identity_report: false,
    },
    {
        name: 'countries:Saudi Arabia',
        alpha3: 'SAU',
        alpha2: 'SA',
        region: 'Asia',
        subregion: 'Western Asia',
        supported_identity_report: true,
    },
    {
        name: 'countries:Senegal',
        alpha3: 'SEN',
        alpha2: 'SN',
        region: 'Africa',
        subregion: 'Western Africa',
        supported_identity_report: false,
    },
    {
        name: 'countries:Serbia',
        alpha3: 'SRB',
        alpha2: 'RS',
        region: 'Europe',
        subregion: 'Southern Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:Seychelles',
        alpha3: 'SYC',
        alpha2: 'SC',
        region: 'Africa',
        subregion: 'Eastern Africa',
        supported_identity_report: false,
    },
    {
        name: 'countries:Sierra Leone',
        alpha3: 'SLE',
        alpha2: 'SL',
        region: 'Africa',
        subregion: 'Western Africa',
        supported_identity_report: false,
    },
    {
        name: 'countries:Singapore',
        alpha3: 'SGP',
        alpha2: 'SG',
        region: 'Asia',
        subregion: 'South-Eastern Asia',
        supported_identity_report: true,
    },
    {
        name: 'countries:Sint Maarten (Dutch part)',
        alpha3: 'SXM',
        alpha2: 'NL',
        region: 'Americas',
        subregion: 'Caribbean',
        supported_identity_report: false,
    },
    {
        name: 'countries:Slovakia',
        alpha3: 'SVK',
        alpha2: 'SK',
        region: 'Europe',
        subregion: 'Eastern Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:Slovenia',
        alpha3: 'SVN',
        alpha2: 'SI',
        region: 'Europe',
        subregion: 'Southern Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:Solomon Islands',
        alpha3: 'SLB',
        alpha2: 'SB',
        region: 'Oceania',
        subregion: 'Melanesia',
        supported_identity_report: false,
    },
    {
        name: 'countries:Somalia',
        alpha3: 'SOM',
        alpha2: 'SO',
        region: 'Africa',
        subregion: 'Eastern Africa',
        supported_identity_report: true,
    },
    {
        name: 'countries:South Africa',
        alpha3: 'ZAF',
        alpha2: 'ZA',
        region: 'Africa',
        subregion: 'Southern Africa',
        supported_identity_report: true,
    },
    {
        name: 'countries:South Georgia and the South Sandwich Islands',
        alpha3: 'SGS',
        alpha2: 'GS',
        region: 'Americas',
        subregion: 'South America',
        supported_identity_report: false,
    },
    {
        name: 'countries:South Sudan',
        alpha3: 'SSD',
        alpha2: 'SS',
        region: 'Africa',
        subregion: 'Northern Africa',
        supported_identity_report: false,
    },
    {
        name: 'countries:Spain',
        alpha3: 'ESP',
        alpha2: 'ES',
        region: 'Europe',
        subregion: 'Southern Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:Sri Lanka',
        alpha3: 'LKA',
        alpha2: 'LK',
        region: 'Asia',
        subregion: 'Southern Asia',
        supported_identity_report: true,
    },
    {
        name: 'countries:Sudan',
        alpha3: 'SDN',
        alpha2: 'SD',
        region: 'Africa',
        subregion: 'Northern Africa',
        supported_identity_report: true,
    },
    {
        name: 'countries:Suriname',
        alpha3: 'SUR',
        alpha2: 'SR',
        region: 'Americas',
        subregion: 'South America',
        supported_identity_report: false,
    },
    {
        name: 'countries:Svalbard and Jan Mayen',
        alpha3: 'SJM',
        alpha2: 'NO',
        region: 'Europe',
        subregion: 'Northern Europe',
        supported_identity_report: false,
    },
    {
        name: 'countries:Swaziland',
        alpha3: 'SWZ',
        alpha2: 'SZ',
        region: 'Africa',
        subregion: 'Southern Africa',
        supported_identity_report: false,
    },
    {
        name: 'countries:Sweden',
        alpha3: 'SWE',
        alpha2: 'SE',
        region: 'Europe',
        subregion: 'Northern Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:Syrian Arab Republic',
        alpha3: 'SYR',
        alpha2: 'SY',
        region: 'Asia',
        subregion: 'Western Asia',
        supported_identity_report: true,
    },
    {
        name: 'countries:Taiwan, Province of China',
        alpha3: 'TWN',
        alpha2: 'TW',
        region: 'Asia',
        subregion: 'Eastern Asia',
        supported_identity_report: true,
    },
    {
        name: 'countries:Tajikistan',
        alpha3: 'TJK',
        alpha2: 'TJ',
        region: 'Asia',
        subregion: 'Central Asia',
        supported_identity_report: true,
    },
    {
        name: 'countries:Tanzania, United Republic of',
        alpha3: 'TZA',
        alpha2: 'TZ',
        region: 'Africa',
        subregion: 'Eastern Africa',
        supported_identity_report: true,
    },
    {
        name: 'countries:Thailand',
        alpha3: 'THA',
        alpha2: 'TH',
        region: 'Asia',
        subregion: 'South-Eastern Asia',
        supported_identity_report: true,
    },
    {
        name: 'countries:Timor-Leste',
        alpha3: 'TLS',
        alpha2: 'TL',
        region: 'Asia',
        subregion: 'South-Eastern Asia',
        supported_identity_report: false,
    },
    {
        name: 'countries:Togo',
        alpha3: 'TGO',
        alpha2: 'TG',
        region: 'Africa',
        subregion: 'Western Africa',
        supported_identity_report: true,
    },
    {
        name: 'countries:Tokelau',
        alpha3: 'TKL',
        alpha2: 'TK',
        region: 'Oceania',
        subregion: 'Polynesia',
        supported_identity_report: false,
    },
    {
        name: 'countries:Tonga',
        alpha3: 'TON',
        alpha2: 'TO',
        region: 'Oceania',
        subregion: 'Polynesia',
        supported_identity_report: false,
    },
    {
        name: 'countries:Trinidad and Tobago',
        alpha3: 'TTO',
        alpha2: 'TT',
        region: 'Americas',
        subregion: 'Caribbean',
        supported_identity_report: true,
    },
    {
        name: 'countries:Tunisia',
        alpha3: 'TUN',
        alpha2: 'TN',
        region: 'Africa',
        subregion: 'Northern Africa',
        supported_identity_report: true,
    },
    {
        name: 'countries:Turkey',
        alpha3: 'TUR',
        alpha2: 'TR',
        region: 'Asia',
        subregion: 'Western Asia',
        supported_identity_report: true,
    },
    {
        name: 'countries:Turkmenistan',
        alpha3: 'TKM',
        alpha2: 'TM',
        region: 'Asia',
        subregion: 'Central Asia',
        supported_identity_report: true,
    },
    {
        name: 'countries:Turks and Caicos Islands',
        alpha3: 'TCA',
        alpha2: 'TC',
        region: 'Americas',
        subregion: 'Caribbean',
        supported_identity_report: true,
    },
    {
        name: 'countries:Tuvalu',
        alpha3: 'TUV',
        alpha2: 'TV',
        region: 'Oceania',
        subregion: 'Polynesia',
        supported_identity_report: true,
    },
    {
        name: 'countries:Uganda',
        alpha3: 'UGA',
        alpha2: 'UG',
        region: 'Africa',
        subregion: 'Eastern Africa',
        supported_identity_report: true,
    },
    {
        name: 'countries:Ukraine',
        alpha3: 'UKR',
        alpha2: 'UA',
        region: 'Europe',
        subregion: 'Eastern Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:United Arab Emirates',
        alpha3: 'ARE',
        alpha2: 'AE',
        region: 'Asia',
        subregion: 'Western Asia',
        supported_identity_report: true,
    },
    {
        name: 'countries:United Kingdom of Great Britain and Northern Ireland',
        alpha3: 'GBR',
        alpha2: 'GB',
        region: 'Europe',
        subregion: 'Northern Europe',
        supported_identity_report: true,
    },
    {
        name: 'countries:United States Minor Outlying Islands',
        alpha3: 'UMI',
        alpha2: 'US',
        region: 'Americas',
        subregion: 'Northern America',
        supported_identity_report: false,
    },
    {
        name: 'countries:United States of America',
        alpha3: 'USA',
        alpha2: 'US',
        region: 'Americas',
        subregion: 'Northern America',
        supported_identity_report: true,
    },
    {
        name: 'countries:Uruguay',
        alpha3: 'URY',
        alpha2: 'UY',
        region: 'Americas',
        subregion: 'South America',
        supported_identity_report: false,
    },
    {
        name: 'countries:Uzbekistan',
        alpha3: 'UZB',
        alpha2: 'UZ',
        region: 'Asia',
        subregion: 'Central Asia',
        supported_identity_report: true,
    },
    {
        name: 'countries:Vanuatu',
        alpha3: 'VUT',
        alpha2: 'VU',
        region: 'Oceania',
        subregion: 'Melanesia',
        supported_identity_report: true,
    },
    {
        name: 'countries:Venezuela (Bolivarian Republic of)',
        alpha3: 'VEN',
        alpha2: 'VE',
        region: 'Americas',
        subregion: 'South America',
        supported_identity_report: true,
    },
    {
        name: 'countries:Viet Nam',
        alpha3: 'VNM',
        alpha2: 'VN',
        region: 'Asia',
        subregion: 'South-Eastern Asia',
        supported_identity_report: true,
    },
    {
        name: 'countries:Virgin Islands (British)',
        alpha3: 'VGB',
        alpha2: 'VG',
        region: 'Americas',
        subregion: 'Caribbean',
        supported_identity_report: true,
    },
    {
        name: 'countries:Virgin Islands (U.S.)',
        alpha3: 'VIR',
        alpha2: 'VI',
        region: 'Americas',
        subregion: 'Caribbean',
        supported_identity_report: false,
    },
    {
        name: 'countries:Wallis and Futuna',
        alpha3: 'WLF',
        alpha2: 'WF',
        region: 'Oceania',
        subregion: 'Polynesia',
        supported_identity_report: false,
    },
    {
        name: 'countries:Western Sahara',
        alpha3: 'ESH',
        alpha2: 'EH',
        region: 'Africa',
        subregion: 'Northern Africa',
        supported_identity_report: false,
    },
    {
        name: 'countries:Yemen',
        alpha3: 'YEM',
        alpha2: 'YE',
        region: 'Asia',
        subregion: 'Western Asia',
        supported_identity_report: false,
    },
    {
        name: 'countries:Zambia',
        alpha3: 'ZMB',
        alpha2: 'ZM',
        region: 'Africa',
        subregion: 'Eastern Africa',
        supported_identity_report: true,
    },
    {
        name: 'countries:Zimbabwe',
        alpha3: 'ZWE',
        alpha2: 'ZW',
        region: 'Africa',
        subregion: 'Eastern Africa',
        supported_identity_report: true,
    },
    {
        name: 'countries:Åland Islands',
        alpha3: 'ALA',
        alpha2: 'AX',
        region: 'Europe',
        subregion: 'Northern Europe',
        supported_identity_report: true,
    },
];
