export enum DocumentType {
    KYCReport = 1,
    AttestationDHébergement = 3,
    CIHébergeur = 4,
    ExtraitRegistreDuCommerceKbis = 5,
    JustificatifDeDomicile = 6,
    PieceDIdentité = 7,
    RecherchesMédias = 10,
    CorrespondancesMail = 12,
    ActeDeVenteImmobilier = 13,
    FormulaireProfilDeRisqueClient = 14,
    HistoriqueTransactionsBSharpe = 15,
    FactureQR = 16,
    ActeDeDécès = 17,
    DocFamille = 18,
    PaiementFacture = 19,
}
