name: 'Build'

on: # yamllint disable-line rule:truthy
    push:
        branches:
            - 'main'

jobs:
    build:
        name: 'Build'

        runs-on: 'ubuntu-latest'

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'yarn'
            - run: yarn
            - run: yarn code:check
            - run: yarn build # Create dist folder
            # Create new commit and push changes to current branch
            - run: |
                  git config --global user.email "github-action@b-sharpe.com"
                  git config --global user.name "Github action"
                  git add .
                  git commit -m "chore: dist folder" --no-verify
                  git push -u origin ${GITHUB_REF##*/}
