name: check code
on:
    push:
        branches-ignore:
            - main
            - release-v**

jobs:
    check-code:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'yarn'
            - run: yarn
            - run: yarn code:check
