name: check code
on:
    push:
        branches-ignore:
            - main

jobs:
    check-code:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 21.7.1
                  cache: 'yarn'
            - run: yarn
            - run: yarn code:check
